/**
 * Intent-first retrieval metadata for the Effect 4 Handbook.
 *
 * This is deliberately a curated decision layer, not a generated inventory of
 * every exported symbol. Each entry should answer a real selection question
 * and point at the concise reference that owns the API facts.
 */
const capabilityImportOverrides = Object.freeze({
  "persistence.store": [
    { path: "effect/unstable/persistence", symbols: ["Persistence", "PersistenceStore", "KeyValueStore"] }
  ],
  "persistence.cache": [
    { path: "effect/unstable/persistence", symbols: ["PersistedCache"] },
    { path: "effect", symbols: ["RequestResolver.persisted"] }
  ],
  "observability.telemetry": [
    { path: "effect", symbols: ["Effect.log", "Effect.withSpan", "Metric"] },
    { path: "effect/unstable/observability", symbols: ["Otlp"] }
  ],
  "testing.effect": [
    { path: "@effect/vitest", symbols: ["it.effect"] },
    { path: "effect/testing", symbols: ["TestClock", "TestConsole"] },
    { path: "effect", symbols: ["Layer.mock"] }
  ]
})

export const capabilities = [
  capability("effect.program", "core", ["Effect", "Effect.gen", "Effect.fn"], "effect", "stable", ["model an asynchronous computation", "compose typed effects", "replace async await"], "The default description type for work that may succeed, fail, or require services.", "The operation is effectful and its success, failure, and requirements should remain visible.", "A plain value, Option, or Result already models the whole operation without services or asynchronous work.", ["option.optional", "result.expected-failure"], "Typed failures use E; defects and interruption remain in Cause.", "R lists required services.", "Lazy until run at an application boundary; fibers are interruptible.", "portable", "foundations/core-runtime-execution.md", "effect"),
  capability("effect.promise-boundary", "core", ["Effect.tryPromise", "Effect.promise", "Effect.callback"], "effect", "stable", ["wrap a promise", "call a promise api", "adapt a callback api", "convert rejection to typed error"], "Adapts foreign asynchronous APIs while keeping failures and cancellation explicit.", "Calling Promise- or callback-based code at an integration boundary.", "Writing async functions throughout Effect services or losing rejection typing with Effect.promise.", ["effect.program"], "tryPromise maps rejection to E; promise rejection is a defect.", "Usually none; the wrapped callback may capture services explicitly.", "Cancellation is cooperative; callback integrations can install a canceler.", "portable", "foundations/core-runtime-execution.md", "1-creating-effects"),
  capability("effect.resource", "core", ["Effect.acquireRelease", "Effect.scoped", "Scope"], "effect", "stable", ["close a resource", "bracket acquire release", "cleanup on interruption", "resource safety"], "Acquires a value into a Scope and registers deterministic cleanup.", "One resource must remain valid for the surrounding scoped operation.", "Returning the resource outside its Scope or using try/finally around lazy Effects.", ["layer.scoped", "resource.refreshable"], "Acquisition may add E; finalizer failures belong to Cause.", "Scope appears in R until Effect.scoped supplies it.", "Finalizer runs when the owning scope closes on success, failure, or interruption.", "portable", "foundations/core-runtime-execution.md", "6-interruption-resource-safety", ["resource-safe-bounded-worker"]),
  capability("effect.fork-scoped", "concurrency", ["Effect.forkChild", "Effect.forkScoped", "Fiber"], "effect", "stable", ["start a child fiber", "cancel background work on shutdown", "structured concurrency"], "Forks work under an explicit parent or Scope instead of leaking a detached fiber.", "Concurrent work must be supervised and interrupted with its owner.", "Work intentionally must outlive its requester and has an explicit global shutdown policy; then use Effect.forkDetach.", ["concurrency.bounded", "effect.resource"], "The child retains its own Exit; joining re-exposes failure.", "The forked Effect's R must be satisfied before forking.", "Child/scoped fibers are interrupted with their parent/scope.", "portable", "foundations/core-runtime-execution.md", "fiber"),
  capability("context.service", "core", ["Context.Service"], "effect", "stable", ["dependency injection", "define a service", "test substitute", "ambient dependency"], "Defines a typed capability that Effects request through R.", "Business logic needs an implementation selected at the composition boundary.", "Passing infrastructure through every function or hiding it in mutable globals.", ["context.reference", "layer.service"], "Service methods decide their own E channels.", "The service identity appears in R until provided.", "A service is identity, not a lifecycle; the supplying Layer owns lifecycle.", "portable", "foundations/services-context-layers.md", "context", ["service-live-test-layers"]),
  capability("context.reference", "core", ["Context.Reference", "References"], "effect", "stable", ["fiber local setting", "default service value", "override runtime policy"], "Defines a context value with a default that can be locally overridden.", "A policy or setting should be readable from context without making every caller provide it.", "A resource or business service requires acquisition and cleanup.", ["context.service", "layer.service"], "Reading a Reference does not add a typed error.", "Its default usually removes the requirement from R.", "Overrides follow context/fiber inheritance rather than resource ownership.", "portable", "foundations/services-context-layers.md", "references"),
  capability("layer.service", "core", ["Layer.succeed", "Layer.effect", "Layer.provide"], "effect", "stable", ["provide a service", "compose dependencies", "build an application layer", "dependency graph"], "Builds and composes service implementations with memoized acquisition.", "Several Effect services must be wired once at the application edge.", "Effect.provide repeated at individual call sites or Layer.merge when one layer needs another as input.", ["context.service", "layer.scoped", "managed-runtime.integration"], "Layer construction exposes its build error E.", "Layer input remains in RIn until provided.", "Memoization is per build MemoMap; ordinary values have no finalizer.", "portable", "foundations/services-context-layers.md", "layer", ["service-live-test-layers"]),
  capability("layer.scoped", "core", ["Layer.effect", "Layer.effectDiscard", "Layer.launch"], "effect", "stable", ["provide a resource service", "application lifetime resource", "start a server", "graceful shutdown"], "Turns scoped acquisition into a reusable service graph with deterministic shutdown.", "A connection pool, server, exporter, or subscription belongs to an application/component lifetime.", "Constructing a resource outside a Layer and discarding its finalizer.", ["effect.resource", "layer.service"], "Acquisition errors are Layer errors; finalizer defects remain in Cause.", "Layer inputs describe prerequisite services.", "The built scope owns all finalizers and closes in reverse acquisition order.", "portable", "foundations/services-context-layers.md", "layer", ["graceful-entrypoint-shutdown"]),
  capability("managed-runtime.integration", "core", ["ManagedRuntime.make", "runtime.runPromise", "runtime.dispose"], "effect", "stable", ["integrate Effect with a framework", "reuse a runtime", "run Effect from callbacks", "dispose application services"], "Builds a reusable runtime for a non-Effect host and exposes explicit disposal.", "A framework owns callbacks and cannot itself run as one Effect program.", "Creating a new runtime per callback or calling Effect.runPromise inside domain services.", ["layer.service", "layer.scoped"], "The instance runPromise method rejects with the squashed Cause unless using an Exit-returning runner.", "The managed Layer satisfies R for submitted Effects.", "Resources live until the instance dispose method runs; disposal must be tied to host shutdown.", "portable", "foundations/core-runtime-execution.md", "managedruntime", ["managed-runtime-integration"]),
  capability("option.optional", "errors", ["Option"], "effect", "stable", ["optional value", "missing value without error", "nullable value", "zero or one"], "Models deliberate absence with no diagnostic payload.", "Absence is expected and needs no reason, services, or asynchronous work.", "The caller needs a failure reason or the operation itself is effectful.", ["result.expected-failure", "effect.program"], "No error channel; None is a value case.", "None.", "Pure value with no lifecycle.", "portable", "foundations/errors-option-result.md", "option"),
  capability("result.expected-failure", "errors", ["Result"], "effect", "stable", ["pure typed error", "validation result", "success or failure value"], "Models pure success or a typed expected failure without an Effect runtime.", "A synchronous calculation needs a useful failure value but no services.", "The operation is asynchronous, interruptible, or requires services.", ["option.optional", "effect.program"], "Failure is stored as data in Result.Failure.", "None.", "Pure value with no lifecycle.", "portable", "foundations/errors-option-result.md", "result"),
  capability("cause.diagnostics", "errors", ["Cause", "Exit", "Effect.exit"], "effect", "stable", ["inspect defects", "inspect interruption", "capture full failure", "sandbox error"], "Preserves typed failures, defects, and interruption as one diagnostic tree.", "Infrastructure or observability code must inspect the complete reason a fiber stopped.", "Routine domain recovery that can use catchTag on E.", ["effect.program", "result.expected-failure"], "Cause contains Fail, Die, Interrupt, and composed causes.", "Effect.exit captures the complete Exit and removes E from the outer Effect without losing its information; Effect.result captures only typed success or failure.", "Exit is the completed immutable outcome of a fiber.", "portable", "foundations/core-runtime-execution.md", "cause"),
  capability("deferred.one-shot", "concurrency", ["Deferred"], "effect", "stable", ["promise cell", "wait for one value", "complete from another fiber", "one shot signal"], "A one-time Effect-aware result completed by one fiber and awaited by many.", "Consumers must wait for one eventual success or typed failure.", "The signal must reopen, buffer many values, or broadcast a sequence.", ["latch.gate", "queue.work", "pubsub.broadcast"], "The completed Deferred can carry E.", "None after construction.", "Single assignment; waiting fibers are interruptible.", "portable", "foundations/core-runtime-execution.md", "deferred"),
  capability("latch.gate", "concurrency", ["Latch"], "effect", "stable", ["open a gate", "pause many fibers", "reusable signal", "wait until ready"], "A gate that can open, close, and release all current waiters.", "Many fibers should pause behind readiness or a reusable phase boundary.", "A value/error must be delivered or work must be buffered.", ["deferred.one-shot", "queue.work"], "Awaiting a Latch does not introduce E.", "None after construction.", "Mutable reusable state; awaiters are interruptible.", "portable", "foundations/core-runtime-execution.md", "latch"),
  capability("queue.work", "concurrency", ["Queue"], "effect", "stable", ["bounded work queue", "producer consumer", "backpressure", "mailbox"], "A point-to-point buffer where each element is taken by one consumer.", "Producers and workers need explicit capacity and backpressure.", "Every subscriber must see every value or the data is naturally a Stream transformation.", ["pubsub.broadcast", "stream.pipeline"], "Queue<A, E> consumers can fail with E when Queue.fail is used; shutdown interrupts suspended offers and takes.", "None after construction.", "Scoped ownership is conventional; bounded offers suspend under backpressure.", "portable", "concurrency/concurrency-coordination.md", "queue", ["resource-safe-bounded-worker"]),
  capability("pubsub.broadcast", "concurrency", ["PubSub"], "effect", "stable", ["broadcast events", "fan out messages", "multiple subscribers", "event bus"], "Publishes each value to every active subscriber according to a capacity strategy.", "Multiple concurrent subscribers must independently observe new values.", "Values must be retained for future subscribers or processed exactly once.", ["queue.work", "subscription-ref.state-stream"], "Publishing/subscribing has no domain E.", "Subscribers require Scope for safe lifetime management.", "Subscriptions are scoped; capacity strategy controls backpressure/dropping/sliding.", "portable", "concurrency/concurrency-coordination.md", "pubsub"),
  capability("semaphore.limit", "concurrency", ["Semaphore", "PartitionedSemaphore"], "effect", "stable", ["mutex", "limit concurrency", "critical section", "per key lock"], "Controls permits around arbitrary Effects, globally or by partition key.", "A shared critical section or reusable resource needs an explicit concurrency limit.", "A finite collection can use a local concurrency option or reusable objects should be pooled.", ["concurrency.bounded", "pool.resources"], "The wrapped Effect retains its E.", "None after construction.", "Permits are released on success, failure, or interruption.", "portable", "concurrency/concurrency-coordination.md", "semaphore"),
  capability("concurrency.bounded", "concurrency", ["Effect.forEach", "Effect.all"], "effect", "stable", ["process array concurrently", "bounded parallel map", "limit parallel requests"], "Uses a local concurrency option for one finite batch of Effects.", "One collection operation needs bounded parallelism without a shared limiter.", "Limits must span unrelated call sites or protect a reusable resource.", ["semaphore.limit", "pool.resources", "stream.pipeline"], "Combines child failures according to the chosen mode.", "Union of child requirements.", "Child fibers remain structured under the parent operation.", "portable", "foundations/core-runtime-execution.md", "4-concurrency"),
  capability("pool.resources", "concurrency", ["Pool"], "effect", "stable", ["resource pool", "connection pool", "reuse expensive objects", "bounded resource acquisition"], "Maintains reusable acquired items between a minimum and maximum size.", "Expensive scoped objects should be reused and cap total simultaneous ownership.", "Only permit counting is needed or the resource provider already supplies pooling.", ["semaphore.limit", "scoped-cache.resource"], "Acquisition/use errors remain typed.", "Scope is required for Pool lifetime and checked-out resources.", "Minimum/fixed items may be preallocated; items are finalized with the Pool.", "portable", "concurrency/concurrency-coordination.md", "pool"),
  capability("ref.atomic-state", "state", ["Ref"], "effect", "stable", ["atomic mutable state", "counter", "shared in memory state"], "Provides lock-free atomic reads and pure updates of one value.", "One in-memory value needs synchronous atomic modification.", "An update itself is effectful, observers need changes, or several references must change atomically.", ["synchronized-ref.effectful", "subscription-ref.state-stream", "stm.transaction"], "Operations do not add E.", "None after construction.", "Lives as long as references to the Ref; no finalizer.", "portable", "concurrency/state-mutable-references.md", "ref"),
  capability("synchronized-ref.effectful", "state", ["SynchronizedRef"], "effect", "stable", ["effectful atomic update", "serialize state transition", "locked ref"], "Serializes effectful modifications of one state cell.", "Computing the next value requires an Effect and concurrent modifications must not overlap.", "Several transactional variables must change together or update logic is pure.", ["ref.atomic-state", "stm.transaction"], "Update Effects contribute E and R.", "Union of services used by update Effects.", "Updates are mutually exclusive; interruption semantics follow the update Effect.", "portable", "concurrency/state-mutable-references.md", "synchronizedref"),
  capability("subscription-ref.state-stream", "state", ["SubscriptionRef", "SubscriptionRef.changes"], "effect", "stable", ["observable state", "watch state changes", "current value plus stream"], "Combines an atomic current value with a Stream of subsequent changes.", "Consumers need both a snapshot and live updates from one state cell.", "Only event broadcast is needed or updates across several cells must be transactional.", ["pubsub.broadcast", "stm.transaction", "atom.graph"], "Reference operations have no domain E; consumers retain Stream errors.", "Subscriptions use Scope through Stream execution.", "The current value persists in memory; change subscriptions are scoped.", "portable", "concurrency/state-mutable-references.md", "subscriptionref"),
  capability("stm.transaction", "state", ["Effect.tx", "TxRef", "TxQueue", "TxHashMap"], "effect", "stable", ["atomic multiple state changes", "software transactional memory", "composable transaction", "retry until state changes"], "Composes several in-memory reads, writes, and waits into one atomic transaction.", "Multiple transactional values or conditions must change consistently under concurrency.", "State must survive a process restart, span machines, or perform an observable external side effect inside the retried transaction body.", ["ref.atomic-state", "sql.client"], "Transactions may fail with typed errors; retries are internal conflicts/explicit retry.", "Effect.tx retains arbitrary service requirements other than the supplied Transaction service, but a body may rerun, so captured services must not perform unsafe observable effects.", "In-memory and process-local; commits atomically or retries.", "portable", "concurrency/software-transactional-memory.md", "the-mental-model"),
  capability("stream.pipeline", "streaming", ["Stream"], "effect", "stable", ["process many values", "incremental pipeline", "backpressure stream", "infinite sequence"], "Describes an effectful, resource-safe sequence consumed incrementally.", "Input may be large/infinite or needs effectful transformations and backpressure.", "All data is small, finite, pure, and already in memory.", ["collection.finite", "sink.consume", "channel.protocol"], "Stream carries E independently from element A.", "R includes services required while pulling.", "Pulling and finalizers live for the run Scope; consumers drive demand.", "portable", "concurrency/streaming-channels.md", "stream"),
  capability("sink.consume", "streaming", ["Sink"], "effect", "stable", ["consume a stream", "stream aggregation", "batch stream output", "fold stream"], "A reusable consumer that transforms a stream's input into a result and possible leftovers.", "Consumption/folding logic should compose independently of the producing Stream.", "A simple one-off runCollect/runFold is clearer or bidirectional protocol control is required.", ["stream.pipeline", "channel.protocol"], "Sink contributes its own E.", "R includes services required by consumption.", "Runs within the Stream execution Scope.", "portable", "concurrency/streaming-channels.md", "sink"),
  capability("channel.protocol", "streaming", ["Channel"], "effect", "stable", ["custom stream transducer", "bidirectional protocol", "typed channel", "low level streaming"], "The lower-level typed engine beneath Stream and Sink with input/output/error channels.", "Implementing framing, codecs, or protocols that need explicit channel topology.", "Ordinary element transformation fits Stream and Sink combinators.", ["stream.pipeline", "sink.consume"], "Separates input error, output error, and done values.", "R covers channel effects.", "Resource ownership follows channel execution Scope.", "portable", "concurrency/streaming-channels.md", "channel"),
  capability("collection.finite", "data", ["Array", "Chunk", "Iterable"], "effect", "stable", ["finite collection", "immutable sequence", "lazy pure iterable", "chunk of values"], "Pure sequence tools for finite or synchronously iterable data already available in memory.", "No asynchronous pull, Effect services, backpressure, or streaming finalizer is required.", "The source may be large/infinite/effectful or must release resources incrementally.", ["stream.pipeline"], "No typed effect error.", "None.", "Pure values; Iterable laziness depends on the chosen combinator/source.", "portable", "data/data-structures.md", "array"),
  capability("schedule.retry", "scheduling", ["Effect.retry", "Schedule"], "effect", "stable", ["retry transient failure", "exponential backoff", "retry with jitter", "retry after"], "Drives repeated attempts from typed failures according to a composable Schedule.", "A failed operation is safe to retry and a policy can decide from E and metadata.", "Repeating successes, polling for values, unsafe non-idempotent writes, or durable retries across restarts.", ["schedule.repeat", "schedule.poll", "workflow.durable"], "The original E remains when the policy stops.", "Schedule may add R; the operation retains its R.", "Lives for one Effect execution and is lost on process restart.", "portable", "concurrency/scheduling-time.md", "schedule", ["typed-retry-testclock"]),
  capability("schedule.repeat", "scheduling", ["Effect.repeat", "Schedule"], "effect", "stable", ["repeat successful effect", "run periodically", "repeat action"], "Schedules another execution after successful completion.", "A successful effect should run again according to a non-durable policy.", "Failures should be retried, values should be polled until a condition, or execution must survive restarts.", ["schedule.retry", "schedule.poll", "workflow.durable"], "An operation failure stops repetition unless handled first.", "Union of Effect and Schedule requirements.", "In-process and interruption-aware; schedule state is not durable.", "portable", "concurrency/scheduling-time.md", "schedule"),
  capability("schedule.poll", "scheduling", ["Effect.repeat", "Schedule.while", "Schedule.passthrough"], "effect", "stable", ["poll until condition", "wait for status", "repeat until value"], "Repeats a successful query until its input/result satisfies a condition.", "The operation succeeds with intermediate values and should stop on a value predicate.", "Failure drives retries or the polling state must survive process restart.", ["schedule.retry", "schedule.repeat", "workflow.durable"], "Typed failures still stop the poll unless separately retried.", "Union of query and Schedule requirements.", "In-process; interruption cancels the current poll/sleep.", "portable", "concurrency/scheduling-time.md", "polling-with-repeat-and-passthrough"),
  capability("schedule.cron", "scheduling", ["Cron", "Schedule.cron"], "effect", "stable", ["cron job", "calendar schedule", "run at a wall clock time", "parse cron expression"], "Parses calendar recurrences and turns them into an in-process Schedule.", "A running process should trigger work at calendar times with explicit time-zone semantics.", "Missed runs must survive restart or one job must be coordinated across a cluster.", ["schedule.repeat", "workflow.durable", "cluster.entity"], "Cron.parse returns a Result for invalid expressions; the resulting Schedule itself does not add a domain failure.", "Schedule execution uses Clock; ordinary runtime services provide it by default.", "In-process and interruption-aware; use durable workflow/cluster scheduling when restart or single-cluster ownership matters.", "portable", "concurrency/scheduling-time.md", "cron"),
  capability("cache.lookup", "caching", ["Cache"], "effect", "stable", ["memoize effectful lookup", "cache a value", "ttl cache", "deduplicate concurrent lookup", "lru cache"], "Caches completed lookup Exits with capacity, time-to-live, and concurrent miss deduplication.", "Repeated keys need bounded in-memory lookup caching, including explicit failure caching semantics.", "Values own scoped resources, data must survive restart, or background refresh is the core requirement.", ["scoped-cache.resource", "resource.refreshable", "request-resolver.batch", "persistence.cache"], "Lookup failures are cached as failed Exits and re-fail E.", "Lookup R is captured when the Cache is built.", "In-memory; entries expire/evict and have no resource finalizer.", "portable", "operations/caching-batching.md", "cache"),
  capability("scoped-cache.resource", "caching", ["ScopedCache"], "effect", "stable", ["cache a resource", "cache scoped resources", "memoize scoped acquisition", "shared keyed resource"], "Caches scoped resources and releases each when its entry is removed or the cache closes.", "Repeated keys acquire expensive resources that require finalization.", "Cached values are ordinary data or freshness should be proactively refreshed.", ["cache.lookup", "resource.refreshable", "pool.resources"], "Acquisition failures remain typed and follow cache semantics.", "Scope owns the cache and cached resources.", "Entry/resource lifetime is bounded by eviction, expiry, and cache Scope.", "portable", "operations/caching-batching.md", "scopedcache"),
  capability("resource.refreshable", "caching", ["Resource"], "effect", "stable", ["background refresh", "refresh a value", "periodically reload configuration", "stale value"], "Maintains one acquired value that can refresh manually or on a Schedule.", "Consumers need a current snapshot with explicit refresh and failure semantics.", "Lookup is keyed, values own independently cached resources, or persistence is required.", ["cache.lookup", "scoped-cache.resource", "layer.scoped"], "Initial/refresh acquisition E is surfaced by Resource.get; failed refresh retains the prior value.", "Acquisition services are captured at construction.", "Scoped; scheduled refresh fiber and value lifetime end with the Scope.", "portable", "foundations/services-context-layers.md", "resource"),
  capability("request-resolver.batch", "caching", ["Request", "RequestResolver", "Effect.request"], "effect", "stable", ["data loader", "batch requests", "deduplicate requests", "n plus one"], "Batches typed requests; RequestResolver.withCache separately adds equality-based sharing of in-flight and completed requests.", "Independent callers issue compatible requests that should coalesce into bulk I/O.", "A simple keyed cache is enough or results must persist across restarts.", ["cache.lookup", "sql.resolver", "persistence.cache"], "Each Request declares its success and typed error.", "Resolver R is required where it is supplied/run.", "Base batching is per execution; withCache uses the request cache, while persisted explicitly adds durable reuse.", "portable", "operations/caching-batching.md", "requestresolver"),
  capability("schema.boundary", "schema", ["Schema", "Schema.decodeUnknownEffect", "Schema.encodeUnknownEffect"], "effect", "stable", ["validate unknown input", "decode json", "encode domain value", "runtime type safety"], "Defines one bidirectional boundary between encoded input and validated domain values.", "Data crosses an untrusted, transport, configuration, or persistence boundary.", "A TypeScript annotation or cast is being used as runtime validation.", ["schema.transform", "schema.class"], "Decoding/encoding fails with Schema.SchemaError.", "Some codecs/checks may require services; common schemas require none.", "Pure description; parser Effects are lazy and interruptible like any Effect.", "portable", "data/schema.md", "schema"),
  capability("schema.transform", "schema", ["Schema.decodeTo", "SchemaGetter", "SchemaTransformation"], "effect", "stable", ["transform encoded value", "parse string to domain", "schema codec transformation", "validate then convert"], "Connects encoded and domain schemas with explicit decode and encode logic.", "Wire/storage representation differs from the domain type.", "A one-way arbitrary map would make encoding impossible or a refinement alone suffices.", ["schema.boundary", "schema.class"], "Transformation failures are SchemaIssue values wrapped in Schema.SchemaError.", "Effectful getters may add requirements.", "Pure codec description unless an Effectful transformation is used.", "portable", "data/schema.md", "6-transformations-decodeto-getters"),
  capability("schema.class", "schema", ["Schema.Class", "Schema.TaggedClass", "Schema.Error", "Schema.TaggedError"], "effect", "stable", ["schema backed class", "tagged error class", "domain model", "serializable error"], "Creates nominal constructors whose fields, decoding, and encoding share one Schema.", "A domain record/error needs runtime validation, construction, and protocol schemas.", "A plain Struct is sufficient or class identity would add no value.", ["schema.boundary", "errors.tagged"], "Schema classes decode with Schema.SchemaError; TaggedError instances can also be Effect failures.", "Normally none.", "Instances are ordinary immutable values; schema metadata is static.", "portable", "data/schema.md", "9-classes-and-tagged-errors"),
  capability("errors.tagged", "errors", ["Data.TaggedError", "Schema.TaggedError", "Effect.catchTag"], "effect", "stable", ["typed domain error", "catch by tag", "model expected failure"], "Uses discriminated errors so recovery can be precise and exhaustive.", "Callers can act on an expected failure as part of the domain contract.", "The condition is an unrecoverable invariant defect or only absence with no explanation.", ["result.expected-failure", "cause.diagnostics", "schema.class"], "The tagged value inhabits E and catchTag narrows it.", "None unless recovery handlers require services.", "Ordinary data; serializability requires an appropriate Schema class/codec.", "portable", "foundations/errors-option-result.md", "effect-error-handling"),
  capability("http.client", "web", ["HttpClient", "HttpClientRequest", "HttpClientResponse"], "effect/unstable/http", "unstable", ["make http request", "fetch api", "http client middleware", "retry http"], "Composable outbound HTTP with typed request/response errors and platform clients.", "Calling external HTTP services or building reusable outbound middleware.", "Defining a contract-first server/client pair controlled by the same codebase.", ["http.api", "rpc.contract"], "Transport/body errors use HttpClientError; schema decoding may add Schema.SchemaError.", "Requires HttpClient, usually supplied by FetchHttpClient or a host layer.", "Response bodies and streaming resources follow the request Scope where applicable.", "host-dependent", "interfaces/http-client.md", "httpclient"),
  capability("http.router", "web", ["HttpRouter", "HttpServerResponse"], "effect/unstable/http", "unstable", ["low level http router", "custom http handler", "serve an endpoint"], "Routes raw HTTP requests to Effect handlers without a shared Schema contract.", "You need low-level control, a small adapter route, or non-contractual HTTP behavior.", "You want generated clients, OpenAPI, typed endpoint payloads, or RPC semantics.", ["http.api", "rpc.contract"], "Handler E is translated by server error handling/respondable rules.", "Requires services used by handlers and an HttpServer to serve.", "Server Layer owns listener lifetime; request resources are scoped.", "host-dependent", "interfaces/http-server.md", "httprouter"),
  capability("http.api", "web", ["HttpApi", "HttpApiEndpoint", "HttpApiBuilder", "HttpApiClient"], "effect/unstable/httpapi", "unstable", ["contract first http api", "generated http client", "openapi server", "typed rest api"], "Defines Schema-backed HTTP endpoints once for server handlers, clients, and OpenAPI.", "External/interoperable HTTP semantics matter and both sides should share a typed contract.", "An internal command/query protocol fits RPC or raw routing is intentionally unconstrained.", ["http.router", "rpc.contract"], "Declared endpoint/middleware errors are typed; transport/decode failures follow client/server adapters.", "Handlers require their service Layers; clients require HttpClient.", "Server/client resources follow their host and request scopes.", "host-dependent", "interfaces/http-api.md", "httpapi", ["schema-httpapi-sql"]),
  capability("rpc.contract", "web", ["Rpc", "RpcGroup", "RpcServer", "RpcClient"], "effect/unstable/rpc", "unstable", ["typed rpc", "command query protocol", "streaming rpc", "internal service client"], "Defines Schema-backed request/response operations independent of a specific transport.", "Both peers use Effect and need typed calls, middleware, batching, or streaming.", "Public REST interoperability and OpenAPI are primary requirements.", ["http.api", "cluster.entity", "workflow.durable"], "Each Rpc declares success/error; transport adds RpcClientError where applicable.", "Client/server layers require their transport and handler services.", "Connection and streaming lifetimes depend on the selected transport.", "transport-dependent", "interfaces/rpc.md", "rpc"),
  capability("sql.client", "data", ["SqlClient", "SqlSchema"], "effect/unstable/sql", "unstable", ["query database", "sql transaction", "parameterized sql", "decode sql rows"], "Provides parameterized tagged-template SQL, transactions, streaming, and Schema row codecs.", "Application data lives in a relational database and explicit SQL is appropriate.", "Only ephemeral in-memory state or a typed request resolver without direct SQL is needed.", ["sql.resolver", "persistence.store", "stm.transaction"], "Database operations fail with SqlError; schema codecs add Schema.SchemaError.", "Requires a provider-specific SqlClient Layer.", "Connections/transactions/streams are scoped; transaction effects share one reserved connection.", "provider-dependent", "interfaces/sql.md", "sqlclient", ["schema-httpapi-sql"]),
  capability("sql.resolver", "data", ["SqlResolver", "SqlSchema"], "effect/unstable/sql", "unstable", ["batch sql queries", "sql data loader", "deduplicate database reads"], "Builds RequestResolvers backed by batched, Schema-decoded SQL operations.", "Repeated entity lookups should batch and deduplicate through Effect requests.", "One ad hoc query is clearer or data needs a general TTL cache instead.", ["request-resolver.batch", "sql.client", "cache.lookup"], "SqlError and Schema.SchemaError flow through declared request errors.", "Requires SqlClient and any schema services.", "Batching follows the request execution; SQL resources are driver-scoped.", "provider-dependent", "interfaces/sql.md", "sqlresolver"),
  capability("persistence.store", "distributed", ["Persistence", "PersistenceStore", "KeyValueStore"], "effect/unstable/persistence", "unstable", ["persist effect result", "current persisted state", "key value storage", "durable state", "store exit"], "Provides Schema-backed persistence abstractions over memory, filesystem, SQL-like, or Redis-style stores.", "A result/value must survive process restart behind a replaceable storage Layer.", "You require event history, workflow replay, or multi-record relational transactions.", ["persistence.cache", "eventlog.history", "workflow.durable", "sql.client"], "Persistence and Schema.SchemaError values remain typed.", "Requires the selected Store/KeyValueStore Layer and codec services.", "Backend determines durability, atomicity, sharing, and cleanup.", "backend-dependent", "tooling/persistence.md", "persistence"),
  capability("persistence.cache", "distributed", ["PersistedCache", "RequestResolver.persisted"], "effect/unstable/persistence", "unstable", ["cache across restart", "persistent cache", "durable request result"], "Persists Schema-backed lookup/request Exits so results can be reused after restart.", "Cached computations are expensive and have stable keys/codecs across deployments.", "An in-memory cache suffices or the operation requires workflow semantics rather than memoization.", ["cache.lookup", "request-resolver.batch", "workflow.durable"], "Stored failed Exits can reproduce typed failures; backend/codec errors are explicit.", "Requires Persistence plus lookup/resolver services.", "Lifetime and sharing follow the persistence backend and TTL policy.", "backend-dependent", "tooling/persistence.md", "persistedcache"),
  capability("workflow.durable", "distributed", ["Workflow", "WorkflowEngine", "Activity"], "effect/unstable/workflow", "unstable", ["durable workflow", "durable orchestration", "resume after restart", "long running process", "durable retry"], "Records workflow progress so deterministic orchestration can resume across failures and ownership moves.", "A long-running process crosses restarts and coordinates idempotent external activities.", "An in-process Schedule is enough or only append-only event history is required.", ["schedule.retry", "eventlog.history", "cluster.entity"], "Workflow/activity definitions declare typed failures; delivery before a recorded result may be at least once.", "Requires WorkflowEngine and activity dependencies.", "Durable state is backend-owned; external side effects still require idempotency.", "backend/distribution-dependent", "systems/workflows-durable-execution.md", "workflow"),
  capability("workflow.activity", "distributed", ["Activity", "Activity.idempotencyKey"], "effect/unstable/workflow", "unstable", ["workflow side effect", "idempotent activity", "external call in workflow"], "Moves nondeterministic/external Effect work behind a durable workflow step.", "Workflow orchestration must call HTTP, SQL, email, or another external side effect.", "Pure deterministic workflow logic or an ordinary non-durable Effect.", ["workflow.durable"], "Activity failures are recorded/retried according to policy; uncertain delivery requires idempotency.", "Activity implementation services are supplied by the worker/runtime.", "Recorded Exit is replayed, but a crash before recording can repeat the side effect.", "backend/distribution-dependent", "systems/workflows-durable-execution.md", "activity"),
  capability("cluster.entity", "distributed", ["Entity", "Sharding", "EntityProxy"], "effect/unstable/cluster", "unstable", ["actor", "distributed actor", "distributed actors", "distributed entity", "sharded state", "route command to owner", "fire and forget entity command"], "Routes typed operations for an entity identity to a single current cluster owner.", "Many keyed logical entities need distributed placement, passivation, and typed messaging.", "Only local state, a durable orchestration, or append-only event history is required.", ["workflow.durable", "eventlog.history", "rpc.contract"], "RPC/entity delivery has cluster errors and at-least-once implications for persisted messages; a volatile discarded call acknowledges runner delivery, not the entity reply.", "Requires cluster Runner/Sharding/storage and entity implementation Layers.", "Ownership moves; entity scopes close on passivation/reassignment.", "distributed", "systems/cluster-sharding.md", "entity"),
  capability("eventlog.history", "distributed", ["EventLog", "EventJournal", "EventGroup"], "effect/unstable/eventlog", "unstable", ["event sourcing", "append event", "projection", "audit history"], "Appends Schema-backed events and derives projections from ordered history.", "The domain needs an auditable event history, replay, and projections.", "Only current state, memoized results, or step-oriented workflow orchestration is needed.", ["persistence.store", "workflow.durable", "cluster.entity"], "Event handlers/journals expose typed domain, persistence, and schema failures.", "Requires an EventJournal and handler services.", "Durability/atomicity depend on journal backend and handler transaction integration.", "backend-dependent", "systems/event-log-event-sourcing.md", "eventlog"),
  capability("atom.graph", "reactivity", ["Atom", "AtomRegistry", "AsyncResult"], "effect/unstable/reactivity", "unstable", ["reactive state graph", "derived state", "effectful atom", "frontend state"], "Describes registry-managed reactive values, dependencies, async state, and invalidation.", "UI/shared reactive state needs derived values, Effect services, caching, or hydration.", "A hot standalone local cell is enough or server coordination belongs in Ref/STM.", ["atom.ref", "subscription-ref.state-stream"], "Effectful atoms expose typed E through AsyncResult; defects remain distinct.", "Runtime atoms require Layers/services through Atom.runtime.", "Registry owns caching, subscriptions, and disposal; providers scope registries.", "browser/framework-oriented", "systems/reactivity-atom.md", "atom"),
  capability("atom.ref", "reactivity", ["AtomRef"], "effect/unstable/reactivity", "unstable", ["local reactive cell", "observable ref", "form state", "fine grained state"], "A standalone synchronous observable cell without an AtomRegistry.", "High-frequency local mutable state needs subscriptions and focused child refs.", "State needs Effect services, async results, dependency graph caching, or hydration.", ["atom.graph", "ref.atomic-state"], "No typed Effect error channel.", "None.", "Lives with ordinary references/subscriptions; no registry disposal.", "portable with framework bindings", "systems/reactivity-atom.md", "atomref"),
  capability("config.decode", "core", ["Config", "ConfigProvider", "Redacted"], "effect", "stable", ["read environment variable", "typed configuration", "secret config", "config validation"], "Builds typed configuration descriptions interpreted by a replaceable provider.", "Application settings and secrets need validation, nesting, defaults, and test providers.", "Reading process.env directly or modeling runtime request data.", ["schema.boundary", "context.service"], "Missing/invalid configuration fails with ConfigError.", "Requires ConfigProvider only when overriding the default provider.", "Configuration is read when the Effect runs; Redacted controls accidental display, not access.", "host/provider-dependent", "foundations/configuration-secrets.md", "config"),
  capability("observability.telemetry", "operations", ["Effect.log", "Effect.withSpan", "Metric", "Otlp"], "effect", "mixed", ["structured logging", "tracing", "metrics", "opentelemetry", "production telemetry"], "Adds structured logs, spans, metrics, and exporter Layers without changing domain results.", "Operational behavior needs correlation, measurement, and export at application boundaries.", "Console logging is used as domain control flow or sensitive values cannot be safely classified.", ["layer.scoped"], "Instrumentation normally preserves E; exporter construction/flush can have separate failures.", "Exporter/tracer/logger services come from Layers.", "Exporter resources are scoped and should be flushed during graceful shutdown.", "host/exporter-dependent", "operations/observability.md", "logger", ["production-observability"]),
  capability("testing.effect", "testing", ["it.effect", "TestClock", "TestConsole", "Layer.mock"], "@effect/vitest", "satellite", ["test Effect code", "virtual time test", "test layer", "deterministic retry test"], "Runs Effects with scoped test services, virtual time, and typed Layer substitution.", "Tests involve Effect failures, fibers, time, resources, services, or Schema properties.", "Using real sleeps, global mocks, or Effect.runPromise inside ordinary test callbacks.", ["schema.boundary", "layer.service"], "Failed Effects are rendered through Cause by the adapter.", "Test services are provided automatically; application services still need Layers.", "Each it.effect has a fresh Scope; shared layer blocks intentionally share state.", "node/vitest", "tooling/testing-dev-tooling.md", "effect-vitest", ["typed-retry-testclock"]),
  capability("ai.language-model", "ai", ["LanguageModel", "Prompt", "Response"], "effect/unstable/ai", "unstable", ["call a language model", "structured model output", "stream model response", "llm provider"], "Provides provider-neutral generation, structured output, streaming, and telemetry contracts.", "Application logic should be portable across model providers and expose typed AI failures.", "Calling a provider SDK directly is intentionally required for an unsupported feature.", ["ai.toolkit", "ai.mcp", "schedule.retry"], "AiError and declared structured-output/schema errors inhabit E.", "Requires a provider LanguageModel Layer and optional telemetry/services.", "Streaming/chat resources and provider clients follow their Layers/Scopes.", "provider-dependent", "systems/ai-language-models.md", "languagemodel"),
  capability("ai.toolkit", "ai", ["Tool", "Toolkit", "Chat"], "effect/unstable/ai", "unstable", ["llm tool calling", "language model tools", "invoke application tools", "agent loop", "structured tool", "chat state"], "Defines Schema-backed tools and resolves model tool calls through typed Effect handlers.", "A model should invoke controlled application capabilities with validated inputs and outputs.", "Arbitrary model text is parsed manually or tools perform unbounded/unobserved side effects.", ["ai.language-model", "ai.mcp"], "Tool handlers declare E; model/tool protocol failures use AiError.", "Handlers require their service Layers.", "Chat/tool loop state is explicit; external effects need normal idempotency/resource rules.", "provider-dependent", "systems/ai-language-models.md", "toolkit"),
  capability("ai.mcp", "ai", ["McpServer", "McpProtocol"], "effect/unstable/ai", "unstable", ["mcp server", "model context protocol", "serve tools over mcp", "stdio mcp"], "Exposes typed tools/resources over a selected MCP protocol and transport.", "External agents need a standards-based boundary to discover and invoke capabilities.", "All tool execution stays inside one application process with no MCP client.", ["ai.toolkit", "http.router"], "Protocol/transport/tool failures are typed by the server and handlers.", "Requires selected protocols, transport/platform services, and tool Layers.", "Stdio/HTTP server Layers own transport lifetime; HTTP mode enforces origin/media contracts.", "host-dependent", "systems/ai-language-models.md", "mcpserver")
]

export const capabilityDomains = Object.freeze({
  core: "Core runtime, errors, services, and configuration",
  concurrency: "Structured concurrency and coordination",
  state: "Mutable and transactional state",
  streaming: "Incremental processing and backpressure",
  data: "Finite data and SQL",
  schema: "Validation and codecs",
  errors: "Absence, expected failures, and diagnostics",
  scheduling: "Retry, repetition, and polling",
  caching: "Caching, refresh, and request batching",
  web: "HTTP and RPC boundaries",
  distributed: "Persistence, workflows, cluster, and event history",
  reactivity: "Reactive graphs and local refs",
  operations: "Observability",
  testing: "Deterministic Effect tests",
  ai: "Language models, tools, and MCP"
})

function capability(id, domain, symbols, importPath, stability, tasks, summary, chooseWhen, avoidWhen, alternatives, errorChannel, requirements, lifetime, platform, page, anchor, snippetIds = []) {
  const imports = capabilityImportOverrides[id] ?? [{ path: importPath, symbols }]
  return Object.freeze({
    id,
    kind: "decision",
    domain,
    symbols,
    importPath,
    imports: Object.freeze(imports.map((entry) => Object.freeze({
      path: entry.path,
      symbols: Object.freeze([...entry.symbols])
    }))),
    stability,
    tasks,
    summary,
    chooseWhen,
    avoidWhen,
    alternatives,
    errorChannel,
    requirements,
    lifetime,
    platform,
    since: Object.freeze({ relation: "availableBy", version: "4.0.0-rc.108" }),
    page,
    anchor,
    snippetIds
  })
}
