packages:
  - validation

allowBuilds:
  msgpackr-extract: false
  protobufjs: true

minimumReleaseAgeExclude:
  - '@effect/ai-anthropic@4.0.0-rc.108'
  - '@effect/ai-openai@4.0.0-rc.108'
  - '@effect/ai-openrouter@4.0.0-rc.108'
  - '@effect/atom-react@4.0.0-rc.108'
  - '@effect/doctest@4.0.0-rc.108'
  - '@effect/opentelemetry@4.0.0-rc.108'
  - '@effect/platform-browser@4.0.0-rc.108'
  - '@effect/platform-bun@4.0.0-rc.108'
  - '@effect/platform-deno@4.0.0-rc.108'
  - '@effect/platform-node-shared@4.0.0-rc.108'
  - '@effect/platform-node@4.0.0-rc.108'
  - '@effect/sql-pg@4.0.0-rc.108'
  - '@effect/sql-pglite@4.0.0-rc.108'
  - '@effect/vitest@4.0.0-rc.108'
  - effect@4.0.0-rc.108
