packages:
  - validation

allowBuilds:
  msgpackr-extract: false
  protobufjs: true

minimumReleaseAgeExclude:
  - '@effect/ai-anthropic@4.0.0'
  - '@effect/ai-openai@4.0.0'
  - '@effect/ai-openrouter@4.0.0'
  - '@effect/ai-typesafe@4.0.0'
  - '@effect/atom-react@4.0.0'
  - '@effect/doctest@4.0.0'
  - '@effect/opentelemetry@4.0.0'
  - '@effect/platform-browser@4.0.0'
  - '@effect/platform-bun@4.0.0'
  - '@effect/platform-deno@4.0.0'
  - '@effect/platform-node-shared@4.0.0'
  - '@effect/platform-node@4.0.0'
  - '@effect/sql-pg@4.0.0'
  - '@effect/sql-pglite@4.0.0'
  - '@effect/vitest@4.0.0'
  - effect@4.0.0
  - '@effect/tsgo-darwin-arm64@0.47.2'
  - '@effect/tsgo-darwin-x64@0.47.2'
  - '@effect/tsgo-linux-arm64@0.47.2'
  - '@effect/tsgo-linux-arm@0.47.2'
  - '@effect/tsgo-linux-x64@0.47.2'
  - '@effect/tsgo-win32-arm64@0.47.2'
  - '@effect/tsgo-win32-x64@0.47.2'
  - '@effect/tsgo@0.47.2'
