import { createHash } from "node:crypto"
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises"
import path from "node:path"
import process from "node:process"
import { fileURLToPath, pathToFileURL } from "node:url"

import { deepDiveAgentSummaries, deepDivePages, handbookPages } from "../handbook.ts"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
export const agentHandbookPath = path.join(root, "dist/effect-4-handbook.md")
/** The llms.txt convention's full-text companion: byte-identical to the concise aggregate. */
export const llmsFullPath = path.join(root, "dist/llms-full.txt")
export const generatedNotice = "<!-- Generated from the concise canonical handbook pages by `pnpm docs:agent`. Long-form deep dives remain in the human site. Do not edit this file directly. Every internal link points at a page's Markdown twin (`.md`), so following links keeps you in Markdown. -->"

export async function buildAgentHandbook() {
  const bodies = await Promise.all(handbookPages.map(async (page) => {
    const sourcePath = path.join(root, "docs", page.source)
    return rewriteSiteLinks(await readFile(sourcePath, "utf8"), page.source).trimEnd()
  }))
  const summaries = deepDivePages
    .filter((page) => page.source !== "deep-dives/index.md")
    .map((page) => {
      const summary = deepDiveAgentSummaries[page.source]
      if (!summary) throw new Error(`Missing agent summary for ${page.source}`)
      return `## ${page.title}\n\n${summary}\n\nHuman deep dive: [${page.source}](./${page.source})`
    })
  const appendix = `# Deep-Dive Architecture Summaries\n\nThese compact maps preserve the composition model in agent context. Fetch a linked long-form page only when the task needs its connected tutorial.\n\n${summaries.join("\n\n")}`
  return `${generatedNotice}\n\n${bodies.join("\n\n")}\n\n${appendix}\n`
}

/**
 * Resolve a page-relative link target (as written in `docs/**`) to the
 * root-relative path of the Markdown twin it should point at.
 *
 * - `core-runtime-execution#effect` from `foundations/x.md` → `foundations/core-runtime-execution.md`
 * - `../deep-dives/` → `deep-dives/index.md`; `../` → `index.md`
 * - an explicit `.md`, `.json`, or `.txt` target is kept as written
 *
 * Returns `undefined` for same-page fragments, absolute paths, and external URLs.
 */
export function resolveMarkdownTarget(href, source) {
  if (href.startsWith("#") || href.startsWith("/") || /^[a-z][a-z0-9+.-]*:/i.test(href)) return undefined
  const boundary = href.search(/[?#]/)
  const pathname = boundary === -1 ? href : href.slice(0, boundary)
  const suffix = boundary === -1 ? "" : href.slice(boundary)
  const directory = path.posix.dirname(source)
  let target = path.posix.normalize(path.posix.join(directory, pathname))
  if (target === "." || target === "./" || target === "") target = "index.md"
  else if (target.endsWith("/")) target = `${target}index.md`
  else if (!/\.(md|json|txt)$/.test(target)) target = `${target}.md`
  return { target, suffix }
}

/** Fence-aware line mapper: `transform` sees every line outside fenced code. */
export function mapOutsideFences(markdown, transform) {
  let fence
  return markdown.split("\n").map((line) => {
    const marker = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/)
    if (marker) {
      if (!fence) fence = { character: marker[1][0], length: marker[1].length }
      else if (marker[1][0] === fence.character && marker[1].length >= fence.length && marker[2].trim() === "") fence = undefined
      return line
    }
    if (fence) return line
    return transform(line)
  }).join("\n")
}

// Source pages link relative to their own topic folders. The combined file and
// the domain bundles are published at the site root, so point every internal
// link at the root-relative Markdown twin while leaving external URLs,
// same-page fragments, and fenced examples untouched.
export function rewriteSiteLinks(markdown, source) {
  return mapOutsideFences(markdown, (line) =>
    line.replace(/(\]\()([^\s)>]+)([^)]*\))/g, (match, opening, href, closing) => {
      // Diagrams live under public/diagrams/, which is published beside the bundles.
      if (href.startsWith("/diagrams/")) return `${opening}.${href}${closing}`
      const resolved = resolveMarkdownTarget(href, source)
      if (!resolved) return match
      return `${opening}./${resolved.target}${resolved.suffix}${closing}`
    }))
}

export function digest(contents) {
  return createHash("sha256").update(contents).digest("hex")
}

async function main() {
  const expected = await buildAgentHandbook()
  const check = process.argv.slice(2).includes("--check")

  if (check) {
    const readOrUndefined = async (file) => {
      try {
        return await readFile(file, "utf8")
      } catch (error) {
        if (error?.code !== "ENOENT") throw error
        return undefined
      }
    }
    const [actual, full] = await Promise.all([readOrUndefined(agentHandbookPath), readOrUndefined(llmsFullPath)])
    if (actual !== expected || full !== expected) {
      console.error("The generated agent handbook or llms-full.txt is missing or stale. Run `pnpm docs:build`.")
      process.exitCode = 1
      return
    }
    console.log(`Combined Markdown and llms-full.txt are current (${handbookPages.length} concise pages, sha256 ${digest(actual)}).`)
    return
  }

  for (const destination of [agentHandbookPath, llmsFullPath]) {
    await mkdir(path.dirname(destination), { recursive: true })
    const temporaryPath = `${destination}.tmp-${process.pid}`
    try {
      await writeFile(temporaryPath, expected)
      await rename(temporaryPath, destination)
    } finally {
      await rm(temporaryPath, { force: true })
    }
  }
  console.log(`Generated ${path.relative(root, agentHandbookPath)} and ${path.relative(root, llmsFullPath)} from ${handbookPages.length} concise pages (sha256 ${digest(expected)}).`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  await main()
}
