import { createHash } from "node:crypto"
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises"
import path from "node:path"
import process from "node:process"
import { fileURLToPath, pathToFileURL } from "node:url"

import { deepDiveAgentSummaries, deepDivePages, handbookPages } from "../handbook.ts"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
export const agentHandbookPath = path.join(root, "dist/effect-4-handbook.md")
export const generatedNotice = "<!-- Generated from the concise canonical handbook pages by `pnpm docs:agent`. Long-form deep dives remain in the human site. Do not edit this file directly. -->"

export async function buildAgentHandbook() {
  const bodies = await Promise.all(handbookPages.map(async (page) => {
    const sourcePath = path.join(root, "docs", page.source)
    return rewriteSiteLinks(await readFile(sourcePath, "utf8"), page.source).trimEnd()
  }))
  const summaries = deepDivePages
    .filter((page) => page.source !== "deep-dives/index.md")
    .map((page) => {
      const summary = deepDiveAgentSummaries[page.source]
      if (!summary) throw new Error(`Missing agent summary for ${page.source}`)
      return `## ${page.title}\n\n${summary}\n\nHuman deep dive: [${page.source}](./${page.source})`
    })
  const appendix = `# Deep-Dive Architecture Summaries\n\nThese compact maps preserve the composition model in agent context. Fetch a linked long-form page only when the task needs its connected tutorial.\n\n${summaries.join("\n\n")}`
  return `${generatedNotice}\n\n${bodies.join("\n\n")}\n\n${appendix}\n`
}

// Source pages link relative to their own topic folders. The combined file is
// published at the site root, so normalize those destinations while leaving
// external URLs, same-page fragments, and fenced examples untouched.
export function rewriteSiteLinks(markdown, source) {
  const directory = path.posix.dirname(source)
  let fence
  return markdown.split("\n").map((line) => {
    const marker = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/)
    if (marker) {
      if (!fence) fence = { character: marker[1][0], length: marker[1].length }
      else if (marker[1][0] === fence.character && marker[1].length >= fence.length && marker[2].trim() === "") fence = undefined
      return line
    }
    if (fence) return line
    return line.replace(/(\]\()([^\s)>]+)([^)]*\))/g, (match, opening, href, closing) => {
      if (href.startsWith("#") || href.startsWith("/") || /^[a-z][a-z0-9+.-]*:/i.test(href)) return match
      const boundary = href.search(/[?#]/)
      const pathname = boundary === -1 ? href : href.slice(0, boundary)
      const suffix = boundary === -1 ? "" : href.slice(boundary)
      const target = path.posix.normalize(path.posix.join(directory, pathname)).replace(/\.md$/, "")
      return `${opening}./${target}${suffix}${closing}`
    })
  }).join("\n")
}

export function digest(contents) {
  return createHash("sha256").update(contents).digest("hex")
}

async function main() {
  const expected = await buildAgentHandbook()
  const check = process.argv.slice(2).includes("--check")

  if (check) {
    let actual
    try {
      actual = await readFile(agentHandbookPath, "utf8")
    } catch (error) {
      if (error?.code !== "ENOENT") throw error
    }
    if (actual !== expected) {
      console.error("The generated agent handbook is missing or stale. Run `pnpm docs:build`.")
      process.exitCode = 1
      return
    }
    console.log(`Combined Markdown is current (${handbookPages.length} concise pages, sha256 ${digest(actual)}).`)
    return
  }

  await mkdir(path.dirname(agentHandbookPath), { recursive: true })
  const temporaryPath = `${agentHandbookPath}.tmp-${process.pid}`
  try {
    await writeFile(temporaryPath, expected)
    await rename(temporaryPath, agentHandbookPath)
  } finally {
    await rm(temporaryPath, { force: true })
  }
  console.log(`Generated ${path.relative(root, agentHandbookPath)} from ${handbookPages.length} concise pages (sha256 ${digest(expected)}).`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  await main()
}
