/**
 * `effect-4-essentials.md`: the default broad read for an agent. It is
 * generated from the concise pages, so it cannot drift from them: for every
 * page its description, and for every section its stability label, opening
 * paragraph, subsection links, and "Reach for it when" line, each pointing at
 * the full section in the page's Markdown twin.
 */
import { handbookGroups, handbookRelease } from "../handbook.ts"
import { rewriteSiteLinks } from "./build-agent-handbook.ts"
import { headingAnchors } from "./build-page-markdown.ts"

export const essentialsFilename = "effect-4-essentials.md"
/** The digest must stay a cheap broad read; the full aggregate exists for exhaustive reads. */
export const essentialsWordBudget = Object.freeze({ min: 20_000, max: 45_000 })

interface Section {
  readonly heading: string
  readonly anchor: string
  readonly lines: Array<string>
  readonly subsections: Array<{ readonly heading: string; readonly anchor: string }>
}

function sectionsOf(markdown: string): { intro: Array<string>; sections: Array<Section> } {
  const anchors = headingAnchors(markdown)
  let anchorIndex = 0
  const intro: Array<string> = []
  const sections: Array<Section> = []
  let fence: { character: string; length: number } | undefined
  for (const line of markdown.split("\n")) {
    const marker = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/)
    if (marker) {
      if (!fence) fence = { character: marker[1][0], length: marker[1].length }
      else if (marker[1][0] === fence.character && marker[1].length >= fence.length && marker[2].trim() === "") fence = undefined
      ;(sections.at(-1)?.lines ?? intro).push("\u0000fence")
      continue
    }
    if (fence) continue
    const heading = line.match(/^(#{1,3})\s+(.+?)\s*#*$/)
    if (heading) {
      const anchor = anchors[anchorIndex++]
      if (heading[1].length === 2) sections.push({ heading: anchor.text, anchor: anchor.anchor, lines: [], subsections: [] })
      else if (heading[1].length === 3 && sections.length) sections.at(-1)!.subsections.push({ heading: anchor.text, anchor: anchor.anchor })
      else if (heading[1].length === 3) intro.push("\u0000heading")
      continue
    }
    ;(sections.at(-1)?.lines ?? intro).push(line)
  }
  return { intro, sections }
}

/** The first prose paragraph: not a callout, table, list, image, caption, or code. */
function firstParagraph(lines: ReadonlyArray<string>): string | undefined {
  const paragraphs: Array<Array<string>> = []
  let current: Array<string> = []
  for (const line of lines) {
    if (line.trim() === "" || line.startsWith("\u0000")) {
      if (current.length) paragraphs.push(current)
      current = []
      if (line === "\u0000heading") break
      continue
    }
    current.push(line)
  }
  if (current.length) paragraphs.push(current)
  const prose = paragraphs.find((paragraph) => {
    const first = paragraph[0].trim()
    return !/^(>|\||[-*+] |\d+\. |!\[|`(effect|@effect\/)[^`]*` — |\*\*Reach for it when\*\*|Official guides?:|\*\*Official|-{3,}$|\*{3,}$)/.test(first) && !/^_[^_].*_$/.test(first)
  })
  return prose?.join(" ").replace(/\s+/g, " ").trim()
}

function labelOf(lines: ReadonlyArray<string>): string | undefined {
  return lines.find((line) => /^`((?:effect|@effect\/)[^`]*)` — (stable|unstable|experimental)\b/.test(line))?.trim()
}

function reachFor(lines: ReadonlyArray<string>): string | undefined {
  return lines.find((line) => line.startsWith("**Reach for it when**"))?.trim()
}

function twin(source: string, anchor?: string): string {
  return `./${source}${anchor ? `#${anchor}` : ""}`
}

export function buildEssentials(sources: ReadonlyMap<string, string>): string {
  const out: Array<string> = [
    `<!-- Generated from the concise canonical handbook pages by \`pnpm docs:pages\`. Do not edit this file directly. -->`,
    "",
    "# The Effect 4 Handbook — Essentials",
    "",
    `The essentials of every concise handbook page for \`effect@${handbookRelease.version}\` (audited ${handbookRelease.auditedAt}), in reading order: what each page and section is for, its stability, and when to reach for it. Every heading links to the full section in that page's Markdown twin; fetch the twin for code, tables, edge cases, and the exact rules. Use [the complete concise handbook](./effect-4-handbook.md) only for an exhaustive review.`,
    ""
  ]
  for (const group of handbookGroups) {
    out.push(`# ${group.text}`, "")
    for (const page of group.items) {
      const markdown = sources.get(page.source)
      if (markdown === undefined) throw new Error(`Essentials: missing source for ${page.source}`)
      const rewrite = (text: string) => rewriteSiteLinks(text, page.source).replace(/\]\(\/diagrams\//g, "](./diagrams/")
      const { intro, sections } = sectionsOf(markdown)
      out.push(`## [${page.title}](${twin(page.source)})`, "", page.description, "")
      const lead = firstParagraph(intro)
      if (lead) out.push(rewrite(lead), "")
      for (const section of sections) {
        out.push(`### [${section.heading}](${twin(page.source, section.anchor)})`, "")
        const label = labelOf(section.lines)
        if (label) out.push(label, "")
        const paragraph = firstParagraph(section.lines)
        if (paragraph) out.push(rewrite(paragraph), "")
        if (section.subsections.length) {
          out.push(`Sections: ${section.subsections.map((sub) => `[${sub.heading.replace(/[[\]]/g, "")}](${twin(page.source, sub.anchor)})`).join(" · ")}`, "")
        }
        const reach = reachFor(section.lines)
        if (reach) out.push(rewrite(reach), "")
      }
    }
  }
  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`
}

export function essentialsWordCount(markdown: string): number {
  return markdown.split(/\s+/).filter(Boolean).length
}
