#!/usr/bin/env node

import { createHash, randomUUID } from "node:crypto"
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises"
import path from "node:path"
import process from "node:process"
import { fileURLToPath, pathToFileURL } from "node:url"

import {
  agentBundles,
  capabilities,
  capabilityDomains,
  handbookRelease,
  sitePages,
  slugifyHeading
} from "../handbook.ts"
import { rewriteSiteLinks } from "./build-agent-handbook.ts"
import { classifyDocExamples } from "./validation/example-model.ts"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const docsRoot = path.join(root, "docs")
export const retrievalOutputDirectory = path.join(root, "dist")
export const catalogFilename = "effect-4-catalog.json"
export const examplesFilename = "effect-4-examples.json"
export const generatedBundleNotice = "<!-- Generated from canonical concise handbook pages by `pnpm docs:retrieval`. Do not edit this file directly. -->"

export const requiredChecksFor = (example) => {
  switch (example.disposition) {
    case "compile":
    case "contextual":
      return ["typescript", "effect"]
    case "run":
      return ["typescript", "effect", "runtime"]
    case "invalid":
      return ["expected-typescript-diagnostic"]
    case "pseudocode":
      return []
    default:
      throw new Error(`Unsupported example disposition ${example.disposition}`)
  }
}

export async function buildRetrievalArtifacts() {
  const { examples, canonicalSourceHash } = await classifyDocExamples()
  const snippets = examples
    .filter((example) => example.disposition === "run")
    .map((example) => ({
      id: example.id,
      source: example.source,
      heading: example.heading,
      language: example.language,
      sha256: example.sha256,
      disposition: example.disposition,
      runtimeCheckId: example.runtime
    }))
    .sort((left, right) => left.id.localeCompare(right.id))
  const pages = new Map()
  for (const page of sitePages) {
    const markdown = await readFile(path.join(docsRoot, page.source), "utf8")
    pages.set(page.source, {
      ...page,
      markdown,
      anchors: scanAnchors(markdown)
    })
  }

  validateCapabilities(pages, snippets)

  const catalog = {
    schemaVersion: 1,
    fieldSemantics: {
      since: "availableBy records the audited release in which the capability is known to exist; it does not claim the exact historical introduction release.",
      snippetIds: "Stable IDs for canonical run examples in this catalog's snippets array; an empty array means the capability currently points only to its canonical reference section."
    },
    handbook: {
      title: "The Effect 4 Handbook",
      effectVersion: handbookRelease.version,
      effectTag: handbookRelease.tag,
      effectCommit: handbookRelease.commit,
      auditedAt: handbookRelease.auditedAt
    },
    domains: capabilityDomains,
    snippets,
    capabilities
  }

  const artifacts = [{
    relativePath: catalogFilename,
    contents: Buffer.from(`${JSON.stringify(catalog, null, 2)}\n`)
  }, {
    relativePath: examplesFilename,
    contents: Buffer.from(`${JSON.stringify({
      schemaVersion: 2,
      artifactKind: "example-inventory",
      handbook: catalog.handbook,
      canonicalSourceHash,
      validationEvidence: "not-included",
      fieldSemantics: {
        requiredChecks: "Validation requirements, not evidence that a check ran. Actual results are regenerated under ignored .validation/generated/** by pnpm docs:examples.",
        compile: "Must pass isolated strict TypeScript and strict Effect diagnostics.",
        contextual: "The exact Markdown body must pass strict TypeScript and Effect diagnostics with one named tracked fixture.",
        run: "Must pass strict TypeScript and Effect diagnostics plus a tracked runtime or Markdown doctest assertion.",
        pseudocode: "Visibly labelled architectural or partial code with a tracked justification; no executable check is required.",
        invalid: "Must produce its one precise expected TypeScript diagnostic."
      },
      totals: {
        disposition: Object.fromEntries(["compile", "contextual", "run", "pseudocode", "invalid"].map((disposition) => [disposition, examples.filter((example) => example.disposition === disposition).length]))
      },
      examples: examples.map((example) => ({
        id: example.id,
        source: example.source,
        heading: example.heading,
        language: example.language,
        startLine: example.startLine,
        endLine: example.endLine,
        sha256: example.sha256,
        disposition: example.disposition,
        classificationSource: example.classificationSource,
        fixture: example.fixture ?? null,
        runtimeCheckId: example.runtime ?? null,
        requiredChecks: requiredChecksFor(example),
        platform: example.platform,
        packages: example.packages,
        ...(example.reason === undefined ? {} : { reason: example.reason }),
        ...(example.diagnostic === undefined ? {} : { expectedDiagnostic: example.diagnostic })
      }))
    }, null, 2)}\n`)
  }]

  for (const bundle of agentBundles) {
    const bodies = bundle.sources.map((source) => {
      const page = pages.get(source)
      assert(page, `${bundle.filename} references unknown page ${source}`)
      return rewriteSiteLinks(page.markdown, page.source).trimEnd()
    })
    artifacts.push({
      relativePath: bundle.filename,
      contents: Buffer.from(`${generatedBundleNotice}\n\n# ${bundle.title}\n\n> Audited ${handbookRelease.auditedAt} against Effect ${handbookRelease.version}. Use the capability catalog for intent-based selection and the linked canonical pages for complete context.\n\n${bodies.join("\n\n")}\n`)
    })
  }

  return { artifacts, catalog }
}

export async function writeRetrievalArtifacts({ outputDirectory = retrievalOutputDirectory } = {}) {
  const result = await buildRetrievalArtifacts()
  for (const artifact of result.artifacts) {
    await writeAtomically(path.join(outputDirectory, artifact.relativePath), artifact.contents)
  }
  return result
}

export async function checkRetrievalArtifacts({ outputDirectory = retrievalOutputDirectory } = {}) {
  const result = await buildRetrievalArtifacts()
  const mismatches = []
  for (const artifact of result.artifacts) {
    let actual
    try {
      actual = await readFile(path.join(outputDirectory, artifact.relativePath))
    } catch (error) {
      if (error?.code !== "ENOENT") throw error
    }
    if (!actual?.equals(artifact.contents)) mismatches.push(artifact.relativePath)
  }
  return { ...result, mismatches, ok: mismatches.length === 0 }
}

function validateCapabilities(pages, snippets) {
  assert(capabilities.length >= 50, `Expected at least 50 curated capabilities; found ${capabilities.length}`)
  const ids = new Set()
  const snippetIds = new Set()
  for (const snippet of snippets) {
    assert(!snippetIds.has(snippet.id), `Duplicate canonical snippet id ${snippet.id}`)
    snippetIds.add(snippet.id)
    assert(snippet.disposition === "run", `${snippet.id} must be classified run`)
    assert(typeof snippet.runtimeCheckId === "string" && snippet.runtimeCheckId !== "", `${snippet.id} must have a tracked runtime check`)
  }
  for (const entry of capabilities) {
    assert(!ids.has(entry.id), `Duplicate capability id ${entry.id}`)
    ids.add(entry.id)
    for (const field of ["id", "kind", "domain", "importPath", "stability", "summary", "chooseWhen", "avoidWhen", "errorChannel", "requirements", "lifetime", "platform", "page", "anchor"]) {
      assert(typeof entry[field] === "string" && entry[field].trim() !== "", `${entry.id} has no ${field}`)
    }
    for (const field of ["symbols", "tasks", "alternatives", "snippetIds"]) {
      assert(Array.isArray(entry[field]), `${entry.id}.${field} must be an array`)
    }
    assert(Array.isArray(entry.imports) && entry.imports.length > 0, `${entry.id}.imports must be a non-empty array`)
    const importedSymbols = []
    for (const imported of entry.imports) {
      assert(typeof imported.path === "string" && imported.path.trim() !== "", `${entry.id} has an invalid import path`)
      assert(Array.isArray(imported.symbols) && imported.symbols.length > 0, `${entry.id} has an empty import group`)
      importedSymbols.push(...imported.symbols)
    }
    assert(JSON.stringify([...importedSymbols].sort()) === JSON.stringify([...entry.symbols].sort()), `${entry.id}.imports must map every symbol exactly once`)
    assert(entry.symbols.length > 0, `${entry.id} has no symbols`)
    assert(entry.tasks.length > 0, `${entry.id} has no task aliases`)
    assert(entry.since?.relation === "availableBy" && entry.since?.version === handbookRelease.version, `${entry.id} has invalid availability metadata`)
    assert(["stable", "unstable", "mixed", "satellite"].includes(entry.stability), `${entry.id} has unsupported stability ${entry.stability}`)
    const page = pages.get(entry.page)
    assert(page, `${entry.id} points at unknown page ${entry.page}`)
    assert(page.anchors.has(entry.anchor), `${entry.id} points at missing anchor ${entry.page}#${entry.anchor}`)
  }
  for (const entry of capabilities) {
    for (const alternative of entry.alternatives) {
      assert(ids.has(alternative), `${entry.id} references unknown alternative ${alternative}`)
      assert(alternative !== entry.id, `${entry.id} references itself as an alternative`)
    }
    for (const snippetId of entry.snippetIds) {
      assert(snippetIds.has(snippetId), `${entry.id} references unknown canonical snippet ${snippetId}`)
    }
  }
  const domainIds = new Set(Object.keys(capabilityDomains))
  for (const entry of capabilities) assert(domainIds.has(entry.domain), `${entry.id} references unknown domain ${entry.domain}`)
  const bundledSources = new Set(agentBundles.flatMap((bundle) => bundle.sources))
  for (const entry of capabilities) assert(bundledSources.has(entry.page), `${entry.id} is not represented in any focused domain bundle`)
}

function scanAnchors(markdown) {
  const anchors = new Set()
  const duplicates = new Map()
  let fence
  for (const line of markdown.split("\n")) {
    const marker = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/)
    if (marker) {
      if (!fence) fence = { character: marker[1][0], length: marker[1].length }
      else if (marker[1][0] === fence.character && marker[1].length >= fence.length && marker[2].trim() === "") fence = undefined
      continue
    }
    if (fence) continue
    const heading = line.match(/^#{1,3}\s+(.+?)\s*#*$/)
    if (!heading) continue
    const base = slugifyHeading(heading[1])
    const count = duplicates.get(base) ?? 0
    duplicates.set(base, count + 1)
    anchors.add(count === 0 ? base : `${base}-${count}`)
  }
  assert(!fence, "Canonical Markdown contains an unclosed fence")
  return anchors
}

async function writeAtomically(destination, contents) {
  await mkdir(path.dirname(destination), { recursive: true })
  const temporary = path.join(path.dirname(destination), `.${path.basename(destination)}.${process.pid}.${randomUUID()}.tmp`)
  try {
    await writeFile(temporary, contents, { flag: "wx" })
    await rename(temporary, destination)
  } finally {
    await rm(temporary, { force: true })
  }
}

export function digest(contents) {
  return createHash("sha256").update(contents).digest("hex")
}

function assert(condition, message) {
  if (!condition) throw new Error(message)
}

async function main() {
  const args = process.argv.slice(2)
  const unknown = args.filter((argument) => argument !== "--check")
  if (unknown.length > 0) throw new Error(`Unknown argument: ${unknown[0]}`)
  if (args.includes("--check")) {
    const result = await checkRetrievalArtifacts()
    if (!result.ok) {
      console.error(`Retrieval artifacts are missing or stale: ${result.mismatches.join(", ")}`)
      process.exitCode = 1
      return
    }
    console.log(`Retrieval artifacts are current (${capabilities.length} capabilities, ${agentBundles.length} domain bundles).`)
    return
  }
  const result = await writeRetrievalArtifacts()
  console.log(`Generated ${result.artifacts.length} retrieval artifacts (${capabilities.length} capabilities; catalog sha256 ${digest(result.artifacts[0].contents)}).`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) await main()
