#!/usr/bin/env node
/**
 * Diagrams are authored as Mermaid sources in `diagrams/*.mmd` and committed
 * as pre-rendered SVGs in `public/diagrams/`, so neither the site build nor CI
 * needs a browser to show them. Pages reference them as ordinary Markdown
 * images (`![alt](/diagrams/<name>.svg)`) followed by an italic caption that
 * carries the diagram's meaning for readers of the Markdown twins.
 *
 *   node scripts/diagrams.ts            re-render every diagram (needs Chrome)
 *   node scripts/diagrams.ts --check    verify every SVG matches its source
 *
 * Rendering uses a pinned @mermaid-js/mermaid-cli through `pnpm dlx` and the
 * Chrome named by HANDBOOK_CHROMIUM (or a standard install path).
 */
import { createHash } from "node:crypto"
import { execFile } from "node:child_process"
import { access, mkdtemp, readdir, readFile, rm, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import process from "node:process"
import { fileURLToPath } from "node:url"
import { promisify } from "node:util"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
export const diagramSourceDirectory = path.join(root, "diagrams")
export const diagramOutputDirectory = path.join(root, "public", "diagrams")
const configPath = path.join(diagramSourceDirectory, "mermaid.config.json")
const mermaidCli = "@mermaid-js/mermaid-cli@12.0.0"
const exec = promisify(execFile)

export async function diagramNames(): Promise<Array<string>> {
  return (await readdir(diagramSourceDirectory)).filter((file) => file.endsWith(".mmd")).map((file) => file.slice(0, -4)).sort()
}

export async function diagramSourceHash(name: string): Promise<string> {
  const source = await readFile(path.join(diagramSourceDirectory, `${name}.mmd`), "utf8")
  const config = await readFile(configPath, "utf8")
  return createHash("sha256").update(`${mermaidCli}\0${config}\0${source}`).digest("hex")
}

function stamp(name: string, hash: string): string {
  return `<!-- Generated by scripts/diagrams.ts from diagrams/${name}.mmd with ${mermaidCli}; source-sha256: ${hash}. Do not edit. -->`
}

/** Every problem with the committed diagrams and the pages that reference them; empty when consistent. */
export async function diagramProblems(markdownBySource: ReadonlyMap<string, string>): Promise<Array<string>> {
  const problems: Array<string> = []
  const names = await diagramNames()
  const outputs = new Set((await readdir(diagramOutputDirectory).catch(() => [])).filter((file) => file.endsWith(".svg")))
  for (const name of names) {
    const file = `${name}.svg`
    if (!outputs.has(file)) {
      problems.push(`public/diagrams/${file} is missing; run node scripts/diagrams.ts`)
      continue
    }
    const svg = await readFile(path.join(diagramOutputDirectory, file), "utf8")
    if (!svg.startsWith(stamp(name, await diagramSourceHash(name)))) {
      problems.push(`public/diagrams/${file} is stale for diagrams/${name}.mmd; run node scripts/diagrams.ts`)
    }
    if (/<foreignObject|https?:\/\/(?!www\.w3\.org)/.test(svg.replace(/<!--[\s\S]*?-->/g, ""))) {
      problems.push(`public/diagrams/${file} has HTML labels or external references`)
    }
  }
  for (const file of outputs) {
    if (!names.includes(file.slice(0, -4))) problems.push(`public/diagrams/${file} has no source in diagrams/`)
  }
  const referenced = new Set<string>()
  for (const [source, markdown] of markdownBySource) {
    const lines = markdown.split("\n")
    lines.forEach((line, index) => {
      for (const match of line.matchAll(/!\[([^\]]*)\]\(\/diagrams\/([a-z0-9-]+)\.svg\)/g)) {
        referenced.add(match[2])
        if (!names.includes(match[2])) problems.push(`docs/${source} references unknown diagram ${match[2]}`)
        if (match[1].trim().length < 20) problems.push(`docs/${source} diagram ${match[2]} needs descriptive alt text`)
        const caption = lines.slice(index + 1).find((next) => next.trim() !== "")
        if (!caption || !/^_[^_].*_$/.test(caption.trim())) problems.push(`docs/${source} diagram ${match[2]} needs an italic caption line after the image`)
      }
    })
  }
  for (const name of names) if (!referenced.has(name)) problems.push(`diagrams/${name}.mmd is not used by any page`)
  return problems
}

async function chromePath(): Promise<string> {
  const candidates = [process.env.HANDBOOK_CHROMIUM, "/usr/bin/google-chrome", "/usr/bin/google-chrome-stable", "/usr/bin/chromium", "/usr/bin/chromium-browser"].filter((value): value is string => Boolean(value))
  for (const candidate of candidates) {
    try {
      await access(candidate)
      return candidate
    } catch {}
  }
  throw new Error(`No Chrome/Chromium executable found. Set HANDBOOK_CHROMIUM. Tried: ${candidates.join(", ")}`)
}

async function render(): Promise<void> {
  const workspace = await mkdtemp(path.join(os.tmpdir(), "handbook-diagrams-"))
  try {
    const puppeteerConfig = path.join(workspace, "puppeteer.json")
    await writeFile(puppeteerConfig, JSON.stringify({ executablePath: await chromePath(), args: ["--no-sandbox", "--headless=new"] }))
    for (const name of await diagramNames()) {
      const output = path.join(workspace, `${name}.svg`)
      await exec("pnpm", ["dlx", mermaidCli, "--quiet", "-p", puppeteerConfig, "-c", configPath, "-b", "transparent", "-I", name, "-i", path.join(diagramSourceDirectory, `${name}.mmd`), "-o", output], {
        env: { ...process.env, PUPPETEER_SKIP_DOWNLOAD: "1" },
        maxBuffer: 16 * 1024 * 1024
      })
      let svg = await readFile(output, "utf8")
      // The CLI may embed a web font; the config already names a system font stack.
      svg = svg.replace(/<style>\/\* Copyright[\s\S]*?<\/style>/g, "").replace(/"Recursive Variable",\s*/g, "")
      // Give the SVG its natural pixel size so an <img> never upscales it; CSS shrinks it to fit.
      const viewBox = svg.match(/viewBox="([-\d.]+) ([-\d.]+) ([\d.]+) ([\d.]+)"/)
      if (!viewBox) throw new Error(`${name}: rendered SVG has no viewBox`)
      const [width, height] = [Math.ceil(Number(viewBox[3])), Math.ceil(Number(viewBox[4]))]
      svg = svg.replace(/<svg([^>]*?) width="100%"/, `<svg$1 width="${width}" height="${height}"`).replace(/ style="max-width: [\d.]+px;[^"]*"/, "")
      await writeFile(path.join(diagramOutputDirectory, `${name}.svg`), `${stamp(name, await diagramSourceHash(name))}\n${svg.trim()}\n`)
      console.log(`Rendered public/diagrams/${name}.svg`)
    }
  } finally {
    await rm(workspace, { recursive: true, force: true })
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  if (process.argv.includes("--check")) {
    const { sitePages } = await import("../handbook.ts")
    const markdown = new Map<string, string>()
    for (const page of sitePages) markdown.set(page.source, await readFile(path.join(root, "docs", page.source), "utf8"))
    const problems = await diagramProblems(markdown)
    for (const problem of problems) console.error(problem)
    if (problems.length) process.exitCode = 1
    else console.log(`Diagrams are current (${(await diagramNames()).length}).`)
  } else {
    await render()
  }
}
