import { lstat, readFile, readdir, stat } from "node:fs/promises"
import path from "node:path"
import process from "node:process"
import { fileURLToPath } from "node:url"

import { agentBundles, sitePages } from "../handbook.ts"
import { buildAgentHandbook } from "./build-agent-handbook.ts"
import { artifactUrl, buildPageMarkdownArtifacts, headingAnchors, llmsFullFilename, moduleIndexFilename, moduleIndexJsonFilename, robotsFilename } from "./build-page-markdown.ts"
import { buildRetrievalArtifacts, catalogFilename, examplesFilename } from "./build-retrieval-artifacts.ts"
import { resolveEditionContext } from "./versions.ts"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const docsRoot = path.join(root, "docs")
const distRoot = path.join(root, "dist")
const base = normalizeBase(option("--base") ?? process.env.VITEPRESS_BASE ?? "/")
const siteUrl = process.env.HANDBOOK_SITE_URL
const origin = "https://handbook.invalid"
const htmlCache = new Map()

// `pnpm docs:build` assembles every edition under `dist/<id>/`; each edition
// was verified by its own build, so the root checks below look only at the
// root edition's files. The editions must still be present.
const editionContext = resolveEditionContext({ base, siteUrl })
const editionDirectories = editionContext.editions.map((entry) => `${entry.id}/`)
const allFiles = await walk(distRoot)
const files = allFiles.filter(({ relative }) => !editionDirectories.some((directory) => relative.startsWith(directory)))
assert(files.length > 0, "VitePress output is empty; run `pnpm docs:build` first")
if (!process.env.HANDBOOK_VERSION) {
  for (const entry of editionContext.editions) {
    assert(allFiles.some(({ relative }) => relative === `${entry.id}/index.html`), `Edition ${entry.id} was not assembled under dist/${entry.id}/; run \`pnpm docs:build\``)
    assert(allFiles.some(({ relative }) => relative === `${entry.id}/llms.txt`), `Edition ${entry.id} has no llms.txt under dist/${entry.id}/`)
  }
}
assert(files.every(({ kind }) => kind === "file"), "The Pages artifact contains a symlink or another non-file entry")
assert(!files.some(({ relative }) => relative.includes("/.vitepress/dist/")), "The Pages artifact contains a nested dist directory")

const totalBytes = files.reduce((sum, file) => sum + file.size, 0)
assert(totalBytes < 100 * 1024 * 1024, `The Pages artifact is unexpectedly large (${formatBytes(totalBytes)})`)

const expectedHtml = new Set(sitePages.map(pageOutputPath))
const actualHtml = files
  .map(({ relative }) => relative)
  .filter((file) => file.endsWith(".html") && file !== "404.html" && file !== "effect-4-handbook.html")
assert(sameSet(new Set(actualHtml), expectedHtml), setDifferenceMessage("rendered page", expectedHtml, new Set(actualHtml)))
assert(files.some(({ relative }) => relative === "effect-4-handbook.html"), "The standalone HTML handbook is missing")
const pageMarkdown = await buildPageMarkdownArtifacts({ base, siteUrl })
const expectedMarkdown = new Set(["effect-4-handbook.md", moduleIndexFilename, ...agentBundles.map((bundle) => bundle.filename), ...sitePages.map((page) => page.source)])
const markdownOutputs = files.map(({ relative }) => relative).filter((file) => file.endsWith(".md"))
assert(sameSet(new Set(markdownOutputs), expectedMarkdown), setDifferenceMessage("generated Markdown", expectedMarkdown, new Set(markdownOutputs)))
for (const name of ["llms.txt", llmsFullFilename, robotsFilename, moduleIndexJsonFilename]) {
  assert(files.some(({ relative }) => relative === name), `The agent entry point ${name} is missing`)
}
for (const artifact of pageMarkdown.artifacts) {
  assert(await isFile(path.join(distRoot, artifact.relativePath)), `${artifact.relativePath} was not published`)
  const actual = await readFile(path.join(distRoot, artifact.relativePath))
  assert(actual.equals(artifact.contents), `${artifact.relativePath} differs from its canonical generated bytes`)
}
assert(pageMarkdown.moduleCount >= 300, `The module index only found ${pageMarkdown.moduleCount} module sections; the label scan is probably broken`)

// Every generated Markdown file must keep an agent inside Markdown: internal
// links resolve to published `.md` twins (or JSON/text artifacts) and their
// fragments name real headings in the target twin.
const markdownAnchorCache = new Map()
async function anchorsFor(relative) {
  if (!markdownAnchorCache.has(relative)) {
    markdownAnchorCache.set(relative, headingAnchors(await readFile(path.join(distRoot, relative), "utf8")).map((heading) => heading.anchor))
  }
  return markdownAnchorCache.get(relative)
}
async function verifyMarkdownLinks(relativePath, markdown) {
  const directory = path.posix.dirname(relativePath)
  for (const reference of markdownReferences(markdown)) {
    assert(!reference.startsWith("/"), `${relativePath} contains a root-absolute link (not portable across bases): ${reference}`)
    const resolved = new URL(reference, `${origin}${base}${directory === "." ? "" : `${directory}/`}`)
    assert(resolved.pathname.startsWith(base), `${relativePath} escapes the configured base ${base}: ${reference}`)
    const target = decodeURIComponent(resolved.pathname.slice(base.length))
    // Diagram images are the one non-Markdown target a twin may reference: the
    // caption after each image carries its meaning for readers who cannot see it.
    const isDiagram = /^diagrams\/[a-z0-9-]+\.svg$/.test(target)
    assert(isDiagram || /\.(md|json|txt)$/.test(target), `${relativePath} links to a non-Markdown route (agents must stay in Markdown): ${reference}`)
    assert(await isFile(path.join(distRoot, target)), `${relativePath} links to a missing artifact: ${reference}`)
    if (resolved.hash && target.endsWith(".md")) {
      const id = decodeURIComponent(resolved.hash.slice(1))
      assert((await anchorsFor(target)).includes(id), `${relativePath} references missing fragment ${resolved.hash} in ${target}`)
    }
  }
}
for (const artifact of pageMarkdown.artifacts) {
  if (artifact.relativePath.endsWith(".md")) await verifyMarkdownLinks(artifact.relativePath, artifact.contents.toString("utf8"))
}
for (const bundle of agentBundles) {
  await verifyMarkdownLinks(bundle.filename, await readFile(path.join(distRoot, bundle.filename), "utf8"))
}
// Links into other editions (and to the root versions.json) leave this
// build's tree; `pnpm docs:versions` asserts those targets once the editions
// are assembled next to the root build.
const edition = editionContext
const otherEditionPrefixes = edition.editions.map((entry) => entry.path).filter((prefix) => prefix !== base)
const isCrossEditionLink = (pathname) =>
  (edition.rootBase !== base && pathname === `${edition.rootBase}versions.json`) ||
  otherEditionPrefixes.some((prefix) => pathname.startsWith(prefix))
const llmsIndex = await readFile(path.join(distRoot, "llms.txt"), "utf8")
for (const reference of markdownReferences(llmsIndex)) {
  const resolved = new URL(reference, `${origin}${base}`)
  assert(resolved.origin === origin || Boolean(siteUrl), `llms.txt contains an unexpected origin: ${reference}`)
  const pathname = siteUrl ? new URL(reference).pathname : resolved.pathname
  if (isCrossEditionLink(pathname)) continue
  assert(pathname.startsWith(base), `llms.txt links outside this build and outside any edition: ${reference}`)
  const target = decodeURIComponent(pathname.slice(base.length))
  assert(await isFile(path.join(distRoot, target)), `llms.txt links to a missing artifact: ${reference}`)
  if (resolved.hash && target.endsWith(".md")) {
    const id = decodeURIComponent(resolved.hash.slice(1))
    assert((await anchorsFor(target)).includes(id), `llms.txt references missing fragment ${resolved.hash} in ${target}`)
  }
}
const retrieval = await buildRetrievalArtifacts()
for (const artifact of retrieval.artifacts) {
  const actual = await readFile(path.join(distRoot, artifact.relativePath))
  assert(actual.equals(artifact.contents), `${artifact.relativePath} differs from its canonical generated bytes`)
}
assert(files.some(({ relative }) => relative === catalogFilename), `The capability catalog ${catalogFilename} is missing`)
assert(files.some(({ relative }) => relative === examplesFilename), `The example inventory ${examplesFilename} is missing`)

const expectedBundle = await buildAgentHandbook()
const publishedBundle = await readFile(path.join(distRoot, "effect-4-handbook.md"), "utf8")
assert(publishedBundle === expectedBundle, "Published effect-4-handbook.md differs from the canonical concise pages")
assert(await readFile(path.join(distRoot, llmsFullFilename), "utf8") === expectedBundle, `Published ${llmsFullFilename} differs from effect-4-handbook.md`)
for (const reference of markdownReferences(publishedBundle)) {
  assert(!reference.startsWith("../"), `Agent Markdown contains a parent-relative link: ${reference}`)
}
await verifyMarkdownLinks("effect-4-handbook.md", publishedBundle)

let renderedCodeBlocks = 0
let sourceCodeBlocks = 0
for (const page of sitePages) {
  const output = pageOutputPath(page)
  const document = await html(output)
  const ids = document.ids
  assert(new Set(ids).size === ids.length, `${output} contains duplicate HTML ids`)
  assert(document.firstH1 === page.title, `${output} rendered the wrong H1`)
  assert(document.markdownAlternates.length === 1, `${output} must advertise exactly one Markdown alternate`)
  assert(document.markdownAlternates[0] === artifactUrl(page.source, base, siteUrl), `${output} advertises the wrong Markdown alternate: ${document.markdownAlternates[0]}`)
  assert(document.describedBy.length === 1, `${output} must advertise exactly one describedby index`)
  assert(document.describedBy[0] === artifactUrl("llms.txt", base, siteUrl), `${output} advertises the wrong describedby index: ${document.describedBy[0]}`)
  assert(document.descriptions.includes(page.description), `${output} does not use the manifest page description`)
  assert(document.markdownToolbars === 1, `${output} must render one page Markdown toolbar`)
  assert(document.relatedTopics === 1, `${output} must render one related-topics block`)

  const markdown = await readFile(path.join(docsRoot, page.source), "utf8")
  // The twin contents line, module index, and llms.txt anchors are computed
  // from Markdown; they must name ids the rendered HTML actually carries.
  for (const heading of headingAnchors(markdown)) {
    assert(ids.includes(heading.anchor), `${output} has no id ${heading.anchor} for heading ${JSON.stringify(heading.text)}`)
  }
  const sourceStructure = scanMarkdown(markdown)
  const pageCodeBlocks = document.codeBlocks
  assert(document.headings === sourceStructure.headings, `${output} rendered ${document.headings} headings for ${sourceStructure.headings} source headings`)
  assert(pageCodeBlocks === sourceStructure.codeBlocks, `${output} rendered ${pageCodeBlocks} code blocks for ${sourceStructure.codeBlocks} source fences`)
  renderedCodeBlocks += pageCodeBlocks
  sourceCodeBlocks += sourceStructure.codeBlocks

  for (const reference of document.references) {
    await verifyReference(reference, output, ids)
  }
}

assert(renderedCodeBlocks === sourceCodeBlocks, "Rendered and source code-block totals differ")
assert(files.some(({ relative }) => /^assets\/.*\.js$/.test(relative)), "The site has no JavaScript asset")
assert(files.some(({ relative }) => /^assets\/.*\.css$/.test(relative)), "The site has no CSS asset")
if (siteUrl) {
  assert(files.some(({ relative }) => relative === "sitemap.xml"), "The production site has no sitemap.xml")
  const normalizedSiteUrl = normalizeSiteUrl(siteUrl)
  const sitemap = await readFile(path.join(distRoot, "sitemap.xml"), "utf8")
  const sitemapLocations = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => decodeHtml(match[1]))
  const expectedLocations = sitePages.map((page) => new URL(page.link.replace(/^\//, ""), normalizedSiteUrl).href)
  assert(JSON.stringify(sitemapLocations.sort()) === JSON.stringify(expectedLocations.sort()), setDifferenceMessage("sitemap URL", new Set(expectedLocations), new Set(sitemapLocations)))
  for (const page of sitePages) {
    const canonical = new URL(page.link.replace(/^\//, ""), normalizedSiteUrl).href
    assert((await html(pageOutputPath(page))).canonicalLinks.includes(canonical), `${page.source} has no canonical URL for ${canonical}`)
  }
}

console.log(`VitePress site verified at base ${base}: ${sitePages.length} pages, ${renderedCodeBlocks} code blocks, ${files.length} files, ${formatBytes(totalBytes)}.`)

async function verifyReference(reference, currentOutput, currentIds) {
  if (!reference || /^(?:https?:|mailto:|tel:|data:|javascript:)/i.test(reference)) return
  const currentRoute = outputToRoute(currentOutput)
  const resolved = new URL(reference, `${origin}${base}${currentRoute}`)
  assert(resolved.origin === origin, `${currentOutput} contains an unexpected URL origin: ${reference}`)
  assert(resolved.pathname.startsWith(base), `${currentOutput} escapes the configured base ${base}: ${reference}`)

  const relative = decodeURIComponent(resolved.pathname.slice(base.length))
  const targetOutput = routeToOutput(relative)
  const targetPath = path.join(distRoot, targetOutput)
  assert(isInside(distRoot, targetPath), `${currentOutput} references a path outside dist: ${reference}`)
  assert(await isFile(targetPath), `${currentOutput} references a missing file: ${reference} -> ${targetOutput}`)

  if (!resolved.hash || !targetOutput.endsWith(".html")) return
  const id = decodeURIComponent(resolved.hash.slice(1))
  const targetIds = targetOutput === currentOutput ? currentIds : await idsFor(targetOutput)
  assert(targetIds.includes(id), `${currentOutput} references missing fragment ${resolved.hash} in ${targetOutput}`)
}

async function idsFor(output) {
  return (await html(output)).ids
}

async function html(output) {
  if (!htmlCache.has(output)) {
    htmlCache.set(output, scanHtml(await readFile(path.join(distRoot, output), "utf8")))
  }
  return htmlCache.get(output)
}

// VitePress owns HTML generation. This scanner verifies its emitted structure
// without pulling in a second HTML implementation solely for build checks.
function scanHtml(source) {
  const lowerSource = source.toLowerCase()
  const ids = []
  const references = []
  const markdownAlternates = []
  const canonicalLinks = []
  const describedBy = []
  const descriptions = []
  const stack = []
  const voidElements = new Set(["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"])
  let headings = 0
  let codeBlocks = 0
  let markdownToolbars = 0
  let relatedTopics = 0
  let firstH1
  let h1Text
  let cursor = 0
  let searchFrom = 0
  let match = nextHtmlTag(source, lowerSource, searchFrom)

  while (match !== undefined) {
    if (h1Text !== undefined) h1Text += decodeHtml(source.slice(cursor, match.start))
    cursor = match.end
    searchFrom = match.end
    const token = match.token
    if (match.declaration) {
      match = nextHtmlTag(source, lowerSource, searchFrom, stack.at(-1)?.rawText)
      continue
    }

    const closing = /^<\//.test(token)
    const nameMatch = token.match(/^<\/?([A-Za-z][\w:-]*)/)
    assert(nameMatch, `Unable to parse generated HTML tag: ${token.slice(0, 80)}`)
    const tagName = nameMatch[1].toLowerCase()

    if (closing) {
      if (tagName === "h1" && h1Text !== undefined) {
        firstH1 ??= h1Text.replace(/\u200b/g, "").replace(/\s+/g, " ").trim()
        h1Text = undefined
      }
      const openIndex = stack.findLastIndex((entry) => entry.tagName === tagName)
      assert(openIndex !== -1, `Generated HTML closes ${tagName} without opening it`)
      stack.length = openIndex
      match = nextHtmlTag(source, lowerSource, searchFrom, stack.at(-1)?.rawText)
      continue
    }

    const attributes = parseAttributes(token, nameMatch[0].length)
    const parent = stack.at(-1)
    const inMain = Boolean(parent?.inMain || tagName === "main")
    const classes = (attributes.class ?? "").split(/\s+/).filter(Boolean)
    const inVpDoc = Boolean(parent?.inVpDoc || (inMain && classes.includes("vp-doc")))

    if (attributes.id !== undefined) ids.push(attributes.id)
    if ((tagName === "a" || tagName === "link") && attributes.href !== undefined) references.push(attributes.href)
    if ((tagName === "script" || tagName === "img") && attributes.src !== undefined) references.push(attributes.src)
    if (tagName === "link" && attributes.rel?.split(/\s+/).includes("alternate") && attributes.type === "text/markdown" && attributes.href) markdownAlternates.push(attributes.href)
    if (tagName === "link" && attributes.rel?.split(/\s+/).includes("describedby") && attributes.href) describedBy.push(attributes.href)
    if (tagName === "link" && attributes.rel?.split(/\s+/).includes("canonical") && attributes.href) canonicalLinks.push(attributes.href)
    if (tagName === "meta" && attributes.name === "description" && attributes.content) descriptions.push(attributes.content)
    if (classes.includes("markdown-toolbar")) markdownToolbars++
    if (classes.includes("related-topics")) relatedTopics++

    if (inVpDoc && /^h[1-3]$/.test(tagName) && attributes["data-generated-heading"] === undefined) {
      headings++
      if (tagName === "h1" && firstH1 === undefined) h1Text = ""
    }
    if (inVpDoc && tagName === "div" && classes.some((name) => name.startsWith("language-"))) codeBlocks++

    const selfClosing = /\/\s*>$/.test(token)
    if (!selfClosing && !voidElements.has(tagName)) {
      stack.push({ tagName, inMain, inVpDoc, rawText: tagName === "script" || tagName === "style" ? tagName : undefined })
    }
    match = nextHtmlTag(source, lowerSource, searchFrom, stack.at(-1)?.rawText)
  }

  assert(stack.length === 0, `Generated HTML has ${stack.length} unclosed element(s)`)
  return { ids, references, headings, codeBlocks, firstH1, markdownAlternates, describedBy, canonicalLinks, descriptions, markdownToolbars, relatedTopics, source }
}

function nextHtmlTag(source, lowerSource, from, rawText) {
  let start = rawText === undefined ? source.indexOf("<", from) : lowerSource.indexOf(`</${rawText}`, from)
  while (start !== -1) {
    if (source.startsWith("<!--", start)) {
      const commentEnd = source.indexOf("-->", start + 4)
      assert(commentEnd !== -1, "Generated HTML contains an unclosed comment")
      return { start, end: commentEnd + 3, token: source.slice(start, commentEnd + 3), declaration: true }
    }

    const next = source[start + 1]
    const isDeclaration = next === "!" || next === "?"
    const isTag = isDeclaration || next === "/" || /[A-Za-z]/.test(next ?? "")
    if (!isTag) {
      start = source.indexOf("<", start + 1)
      continue
    }

    let quote
    let end = start + 1
    for (; end < source.length; end++) {
      const character = source[end]
      if (quote !== undefined) {
        if (character === quote) quote = undefined
      } else if (character === "\"" || character === "'") {
        quote = character
      } else if (character === ">") {
        end++
        break
      }
    }
    assert(end <= source.length && source[end - 1] === ">", "Generated HTML contains an unclosed tag")
    return { start, end, token: source.slice(start, end), declaration: isDeclaration }
  }
  return undefined
}

function parseAttributes(token, nameEnd) {
  const attributes = {}
  const source = token.slice(nameEnd, token.length - 1).replace(/\/\s*$/, "")
  const pattern = /([^\s=/>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g
  let match
  while ((match = pattern.exec(source)) !== null) {
    attributes[match[1].toLowerCase()] = decodeHtml(match[2] ?? match[3] ?? match[4] ?? "")
  }
  return attributes
}

function decodeHtml(value) {
  const named = { amp: "&", apos: "'", gt: ">", lt: "<", nbsp: "\u00a0", quot: "\"" }
  return value.replace(/&(#x[\da-f]+|#\d+|amp|apos|gt|lt|nbsp|quot);/gi, (entity, body) => {
    if (body[0] !== "#") return named[body.toLowerCase()] ?? entity
    const hexadecimal = body[1].toLowerCase() === "x"
    const codePoint = Number.parseInt(body.slice(hexadecimal ? 2 : 1), hexadecimal ? 16 : 10)
    return Number.isSafeInteger(codePoint) ? String.fromCodePoint(codePoint) : entity
  })
}

function pageOutputPath(page) {
  return page.source === "index.md" ? "index.html" : page.source.replace(/\.md$/, ".html")
}

function outputToRoute(output) {
  if (output === "index.html") return ""
  return output.replace(/\.html$/, "")
}

function routeToOutput(relative) {
  const clean = relative.replace(/^\/+/, "")
  if (clean === "") return "index.html"
  if (path.posix.extname(clean)) return clean
  return `${clean.replace(/\/$/, "/index")}.html`
}

function scanMarkdown(markdown) {
  let headings = 0
  let codeBlocks = 0
  let fence
  for (const line of markdown.split("\n")) {
    const marker = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/)
    if (marker) {
      if (!fence) {
        fence = { character: marker[1][0], length: marker[1].length }
        codeBlocks++
      } else if (marker[1][0] === fence.character && marker[1].length >= fence.length && marker[2].trim() === "") {
        fence = undefined
      }
      continue
    }
    if (!fence && /^#{1,3}\s+/.test(line)) headings++
  }
  assert(!fence, "Source Markdown contains an unclosed code fence")
  return { headings, codeBlocks }
}

function markdownReferences(markdown) {
  const references = []
  let fence
  for (const line of markdown.split("\n")) {
    const marker = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/)
    if (marker) {
      if (!fence) fence = { character: marker[1][0], length: marker[1].length }
      else if (marker[1][0] === fence.character && marker[1].length >= fence.length && marker[2].trim() === "") fence = undefined
      continue
    }
    if (fence) continue
    for (const match of line.matchAll(/\]\(([^\s)>]+)(?:\s+[^)]*)?\)/g)) {
      const reference = match[1]
      if (reference && !reference.startsWith("#") && !/^[a-z][a-z0-9+.-]*:/i.test(reference)) references.push(reference)
    }
  }
  return references
}

async function walk(directory, prefix = "") {
  const entries = await readdir(directory, { withFileTypes: true })
  const output = []
  for (const entry of entries) {
    const relative = path.posix.join(prefix, entry.name)
    const absolute = path.join(directory, entry.name)
    const metadata = await lstat(absolute)
    if (metadata.isDirectory()) output.push(...await walk(absolute, relative))
    else output.push({ relative, size: metadata.size, kind: metadata.isFile() ? "file" : metadata.isSymbolicLink() ? "symlink" : "other" })
  }
  return output
}

async function isFile(file) {
  try {
    return (await stat(file)).isFile()
  } catch (error) {
    if (error?.code === "ENOENT") return false
    throw error
  }
}

function isInside(parent, child) {
  const relative = path.relative(parent, child)
  return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative)
}

function normalizeBase(input) {
  const trimmed = input.trim()
  if (trimmed === "" || trimmed === "/") return "/"
  const segments = trimmed.split("/").filter(Boolean)
  assert(!segments.some((segment) => segment === "." || segment === ".."), `Invalid base path: ${JSON.stringify(input)}`)
  return `/${segments.join("/")}/`
}

function normalizeSiteUrl(input) {
  const url = new URL(input)
  url.hash = ""
  url.search = ""
  if (!url.pathname.endsWith("/")) url.pathname += "/"
  return url.href
}

function option(name) {
  const args = process.argv.slice(2).filter((arg) => arg !== "--")
  const index = args.indexOf(name)
  if (index === -1) return undefined
  assert(args[index + 1], `${name} requires a value`)
  return args[index + 1]
}

function sameSet(left, right) {
  return left.size === right.size && [...left].every((value) => right.has(value))
}

function setDifferenceMessage(label, expected, actual) {
  const missing = [...expected].filter((file) => !actual.has(file))
  const extra = [...actual].filter((file) => !expected.has(file))
  return `Unexpected ${label} inventory. Missing: ${missing.join(", ") || "none"}. Extra: ${extra.join(", ") || "none"}.`
}

function formatBytes(bytes) {
  return `${(bytes / 1024 / 1024).toFixed(1)} MiB`
}

function assert(condition, message) {
  if (!condition) {
    console.error(`Site verification failed: ${message}`)
    process.exit(1)
  }
}
